#!/bin/bash
#SBATCH --job-name=job	  # Job name
#SBATCH --partition=batch               # Partition (queue) name, i.e., highmem_p
#SBATCH --ntasks=1                          # Run a single task
#SBATCH --cpus-per-task=28                  # Number of CPU cores per task
#SBATCH --mem=120gb                          # Job memory request
#SBATCH --time=72:00:00                     # Time limit hrs:min:sec
#SBATCH --output=file.out         # Standard output log
#SBATCH --error=file.err          # Standard error log
#SBATCH --mail-type=END,FAIL                # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=jts34805@uga.edu   # Where to send mail
#SBATCH --export=NONE                       # do not load any env variables to compute node

ml fastp/0.23.2

fastp -i bonnmu/rawdata/SRR_1 -o bonnmu/processed/SRR_1A -t 23? A -G -Q -L 
fastp -i bonnmu/processed/SRR_1A -I bonnmu/rawdata/SRR_2 -o bonnmu/processed/SRR_1B_001.fastq.gz -O bonnmu/processed/SRR_2B_001.fastq.gz -U --umi_loc read1 --umi_len 6 --umi_prefix TIR -h fastp.html -A -G -Q -L

fastp -i bonnmu/processed/SRR_1B -I processed/R2B_001.fastq.gz -o filtered/NA17-12-LEAF_R1_001.fastq.gz -O filtered/NA17-12-LEAF_R2_001.fastq.gz --length_required 40 --trim_poly_x --cut_tail --adapter_fasta /scratch/jts34805/adapter.fa
