#!/bin/bash
#SBATCH --job-name=job	  # Job name
#SBATCH --partition=batch               # Partition (queue) name, i.e., highmem_p
#SBATCH --ntasks=1                          # Run a single task
#SBATCH --cpus-per-task=28                  # Number of CPU cores per task
#SBATCH --mem=120gb                          # Job memory request
#SBATCH --time=72:00:00                     # Time limit hrs:min:sec
#SBATCH --output=file.out         # Standard output log
#SBATCH --error=file.err          # Standard error log
#SBATCH --mail-type=END,FAIL                # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=jts34805@uga.edu   # Where to send mail
#SBATCH --export=NONE                       # do not load any env variables to compute node

ml fastp/0.23.2
ml SAMtools
ml Bowtie2
ml UMI-tools

fastp -i bonnmu/rawdata/SRR_2 -o bonnmu/processed/SRR_2A -f 23 A -G -Q -L 
fastp -i bonnmu/processed/SRR_2A -I bonnmu/rawdata/SRR_1 -o bonnmu/processed/SRR_1B_001.fastq.gz -O bonnmu/processed/SRR_2B_001.fastq.gz -U --umi_loc read2 --umi_len 6 --umi_prefix TIR -h fastp.html -A -G -Q -L

fastp -w 8 -i bonnmu/processed/SRR_R1B.fastq.gz -I bonnmu/processed/SRR_R2B.fastq.gz -o bonnmu/filtered/SRR_R1.fastq.gz -O filtered/SRR_R2.fastq.gz --length_required 40 --trim_poly_x --cut_tail --adapter_fasta /scratch/jts34805/bonmu/adapter.fa

bowtie2 --threads 8 -x /scratch/jts34805/remapdir/W22Build/W22chrscaff --phred33 -X 1000 --no-mixed --no-discordant -1 filtered/SRR_R1.fastq.gz -2 filtered/SRR_R2.fastq.gz -S mapped/SRR.sam

samtools view -@ 8 -b -o mapped/SRR.bam  mapped/SRR.sam
samtools sort -@ 8 mapped/SRR.bam -o mapped/SRR.bam
samtools index -@ 8 mapped/SRR.bam

