#!/bin/bash
#SBATCH --job-name=Dumper24	  # Job name
#SBATCH --partition=batch               # Partition (queue) name, i.e., highmem_p
#SBATCH --ntasks=1                          # Run a single task
#SBATCH --cpus-per-task=28                  # Number of CPU cores per task
#SBATCH --mem=120gb                          # Job memory request
#SBATCH --time=72:00:00                     # Time limit hrs:min:sec
#SBATCH --output=file.out         # Standard output log
#SBATCH --error=file.err          # Standard error log
#SBATCH --mail-type=END,FAIL                # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=jts34805@uga.edu   # Where to send mail
#SBATCH --export=NONE                       # do not load any env variables to compute node
cd $SLURM_SUBMIT_DIR
