#!/bin/bash
#SBATCH --job-name=Decemeber2023Sequencing
#SBATCH --partition=batch
#SBATCH --ntasks=8
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=2
#SBATCH --time=165:00:00
#SBATCH --mem=200gb

cd $SLURM_SUBMIT_DIR

ml fastp
ml Bowtie2
ml SAMtools
ml UMI-tools

for file in rawdata/*R1*
do
        file2="${file:8:-15}"
        fastp -w 8 -i $file -o processed/"$file2""R1A.fastq.gz" -f 23 -A -G -Q -L

        fastp -i processed/"$file2""R1A.fastq.gz" -I rawdata/"$file2""R2_001.fastq.gz" -o processed/"$file2""R1B.fastq.gz" -O processed/"$file2""R2B.fastq.gz" -U --umi_loc read1 --umi_len 6 --umi_prefix $

        fastp -i processed/"$file2""R1B.fastq.gz" -I processed/"$file2""R2B.fastq.gz" -o processed/"$file2""R1C.fastq.gz" -O processed/"$file2""R2C.fastq.gz" -U --umi_loc read2 --umi_len 8 --umi_prefix U$
        fastp -i processed/"$file2""R1C.fastq.gz" -I processed/"$file2""R2C.fastq.gz" -o filtered/"$file2""R1.fastq.gz" -O filtered/"$file2""R2.fastq.gz" -U --umi_loc read2 --umi_len 11 --umi_prefix BC -$




bowtie2 --threads 8 -x /scratch/jts34805/B73V5Build/ --phred33 -X 1000 --no-mixed --no-discordant -1 filtered/"$file2""R1.fastq.gz" -2 filtered/"$file2""R2.fastq.gz" | samtools view -@ 8 -b -o mapped/"$f$


        samtools sort -@ 8 mapped/"$file2"".bam" -o mapped/"$file2"".bam"
        samtools index -@ 8 mapped/"$file2"".bam"


        umi_tools group -I mapped/"$file2"".bam" --paired --chimeric-pairs discard --unpaired-reads discard --output-bam -S dedup/"$file2"".Dedup.bam"


        samtools view -f 64 -F 4 dedup/"$file2"".Dedup.bam" | awk -F" " '{split($1, a, "_"); print $3, $4, $8, $9, substr(a[2],1,6), substr(a[3],1,8), $5, length($10), a[4]}' > txtfiles/"$file2"".txt"

done





                                                                                
