#!/bin/bash
#SBATCH --job-name=Dumper24	  # Job name
#SBATCH --partition=batch               # Partition (queue) name, i.e., highmem_p
#SBATCH --ntasks=1                          # Run a single task
#SBATCH --cpus-per-task=28                  # Number of CPU cores per task
#SBATCH --mem=120gb                          # Job memory request
#SBATCH --time=72:00:00                     # Time limit hrs:min:sec
#SBATCH --output=log_all_plants_ortho_finder.subset.%j.out         # Standard output log
#SBATCH --error=log_all_plants_ortho_finder.subset.%j.err          # Standard error log
#SBATCH --mail-type=END,FAIL                # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=jts34805@uga.edu   # Where to send mail
#SBATCH --export=NONE                       # do not load any env variables to compute node
cd $SLURM_SUBMIT_DIR
module load SRA-Toolkit/2.11.1-centos_linux64

fastq-dump --split-files --gzip SRR11657724 
fastq-dump --split-files --gzip SRR11657725 
fastq-dump --split-files --gzip SRR11657726 
fastq-dump --split-files --gzip SRR11657727 
fastq-dump --split-files --gzip SRR11657728 
fastq-dump --split-files --gzip SRR11657729 
fastq-dump --split-files --gzip SRR11657730 
fastq-dump --split-files --gzip SRR11657731 
fastq-dump --split-files --gzip SRR11657732 
fastq-dump --split-files --gzip SRR11657733 
fastq-dump --split-files --gzip SRR11657734 
fastq-dump --split-files --gzip SRR11657735 
fastq-dump --split-files --gzip SRR11657736 
fastq-dump --split-files --gzip SRR11657737 
fastq-dump --split-files --gzip SRR11657738 
fastq-dump --split-files --gzip SRR11657739 
fastq-dump --split-files --gzip SRR11657740 
fastq-dump --split-files --gzip SRR11657741 
fastq-dump --split-files --gzip SRR11657742 
fastq-dump --split-files --gzip SRR11657743 
fastq-dump --split-files --gzip SRR11657744 
fastq-dump --split-files --gzip SRR11657745 
fastq-dump --split-files --gzip SRR11639190 
fastq-dump --split-files --gzip SRR948365 
