#!/bin/bash
#SBATCH --job-name=Mapping50libsB73
#SBATCH --partition=batch
#SBATCH --ntasks=16
#SBATCH --nodes=8
#SBATCH --ntasks-per-node=2
#SBATCH --constraint=AMD
#SBATCH --time=160:00:00
#SBATCH --mem=200gb

cd $SLURM_SUBMIT_DIR

mkdir mapped
mkdir dedup
mkdir txtfiles
ml Bowtie2
ml SAMtools
ml UMI-tools/1.0.1-foss-2019b-Python-3.7.4


for file in filtered/*R1*
do 

  file2="${file:9:-11}"
bowtie2 --threads 16 -x /scratch/jts34805/B73V5Build/B73V5 --phred33 -X 1000 --no-mixed --no-discordant -1 filtered/"$file2""R1.fastq.gz" -2 filtered/"$file2""R2.fastq.gz" | samtools view -@ 16 -b -o mapped/"$file2"".bam"

samtools sort -@ 16 mapped/"$file2"".bam" -o mapped/"$file2"".bam"
samtools index -@ 16 mapped/"$file2"".bam"


umi_tools group -I mapped/"$file2"".bam" --paired --chimeric-pairs discard --unpaired-reads discard --output-bam -S dedup/"$file2"".Dedup.bam"

samtools view -f 64 -F 4 dedup/"$file2"".Dedup.bam" | awk -F" " '{sub(/.*TIR_/,"",$1); sub(/BX:Z:/,"",$(NF)); print $3, $4, $9, $1, $(NF), $5, length($10), $10, $8}' | awk '{sub(/:UMI_.*/,"",$4); print $1, $2, $9, $3, $4, $5, $6, $7, $8}' > txtfiles/"$file2"".txt"

done


