#!/bin/bash
#SBATCH --job-name=MergeBams
#SBATCH --partition=batch
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --time=165:00:00
#SBATCH --mem=50gb



cat A75_S73_L003_R1_001.fastq.gz /scratch/jts34805/October2023Museq/rawdata/A75_6060_S13_L001_R1_001.fastq.gz /scratch/jts34805/December2023MuSeq/rawdata/Brad_A75_S46_R1_001.fastq.gz > merged/A75_April_Merged_R1.fastq.gz 
cat A75_S73_L003_R2_001.fastq.gz /scratch/jts34805/October2023Museq/rawdata/A75_6060_S13_L001_R2_001.fastq.gz /scratch/jts34805/December2023MuSeq/rawdata/Brad_A75_S46_R2_001.fastq.gz > merged/A75_April_Merged_R2.fastq.gz 

cat B75_S82_L003_R1_001.fastq.gz /scratch/jts34805/December2023MuSeq/rawdata/Brad_B75_S40_R1_001.fastq.gz > merged/B75_April_Merged_R1.fastq.gz
cat B75_S82_L003_R2_001.fastq.gz /scratch/jts34805/December2023MuSeq/rawdata/Brad_B75_S40_R2_001.fastq.gz > merged/B75_April_Merged_R2.fastq.gz

cat MI-2_S84_L003_R1_001.fastq.gz /scratch/jts34805/December2023MuSeq/rawdata/Brad_MI-2_S26_R1_001.fastq.gz > merged/MI-2_April_Merged_R1.fastq.gz
cat MI-2_S84_L003_R2_001.fastq.gz /scratch/jts34805/December2023MuSeq/rawdata/Brad_MI-2_S26_R2_001.fastq.gz > merged/MI-2_April_Merged_R2.fastq.gz

cat MI-3T_S86_L003_R1_001.fastq.gz /scratch/jts34805/December2023MuSeq/rawdata/Brad_MI-3T_S28_R1_001.fastq.gz > merged/MI-3T_April_Merged_R1.fastq.gz
cat MI-3T_S86_L003_R2_001.fastq.gz /scratch/jts34805/December2023MuSeq/rawdata/Brad_MI-3T_S28_R2_001.fastq.gz > merged/MI-3T_April_Merged_R2.fastq.gz

cat MI-3_S85_L003_R1_001.fastq.gz /scratch/jts34805/December2023MuSeq/rawdata/Brad_MI-3_S27_R1_001.fastq.gz > merged/MI-3_April_Merged_R1.fastq.gz
cat MI-3_S85_L003_R2_001.fastq.gz /scratch/jts34805/December2023MuSeq/rawdata/Brad_MI-3_S27_R2_001.fastq.gz > merged/MI-3_April_Merged_R2.fastq.gz

cat B78_S75_L003_R1_001.fastq.gz /scratch/jts34805/October2023Museq/rawdata/B78_6060_S14_L001_R1_001.fastq.gz /scratch/jts34805/December2023MuSeq/rawdata/Brad_B78_S47_R1_001.fastq.gz > merged/B78_April_Merged_R1.fastq.gz
cat B78_S75_L003_R2_001.fastq.gz /scratch/jts34805/October2023Museq/rawdata/B78_6060_S14_L001_R2_001.fastq.gz /scratch/jts34805/December2023MuSeq/rawdata/Brad_B78_S47_R2_001.fastq.gz > merged/B78_April_Merged_R2.fastq.gz
 
cat B79_S76_L003_R1_001.fastq.gz /scratch/jts34805/October2023Museq/rawdata/B79_6060_S15_L001_R1_001.fastq.gz /scratch/jts34805/December2023MuSeq/rawdata/Brad_B79_S48_R1_001.fastq.gz > merged/B79_April_Merged_R1.fastq.gz 
cat B79_S76_L003_R2_001.fastq.gz /scratch/jts34805/October2023Museq/rawdata/B79_6060_S15_L001_R2_001.fastq.gz /scratch/jts34805/December2023MuSeq/rawdata/Brad_B79_S48_R2_001.fastq.gz > merged/B79_April_Merged_R2.fastq.gz


