#!/bin/bash
#SBATCH --job-name=July2023Sequencing
#SBATCH --partition=batch
#SBATCH --ntasks=8
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=2
#SBATCH --constraint=AMD
#SBATCH --time=165:00:00
#SBATCH --mem=200gb

cd $SLURM_SUBMIT_DIR

ml fastp
ml Bowtie2
ml SAMtools
for file in "rawdata/"*_R1_*.gz
do
	file2="${file:8:-12}"
	### Remove TIR region and add validation sequence to read header ###
	fastp -w 8 -i $file -o processed/"$file2""1A.fq.gz" -f 23 -A -G -Q -L
	fastp -w 8 -i processed/"$file2""1A.fq.gz" -o filtered/"$file2""R1.fq.gz" -U --umi_loc read1 --umi_len 6 --umi_prefix TIR -h "July2023Museq/fastp/""$file2"".html" --length_required 40 --trim_poly_x --cut_tail --adapter_fasta /scratch/jts34805/remapdir/adapter.fa

	### Map to genome ###
	bowtie2 --threads 8 -x scratch/jts34805/W22Build/W22chrscaff --phred33 -U filtered/"$file2""R1.fq.gz" | samtools view -bS > mapped/"$file2"".bam"
	
	### Deduplicate reads using UMIs ###
	samtools sort -@ 8 mapped/"$file2"".bam" -o "mapped""$file2"".bam"
	samtools index -@ 8 mapped/"$file2"".bam"
	### Prepare bam files for R ###
samtools view -F 4 mapped/"$file2"".bam" | awk -F" " '{sub(/.*TIR_/,"",$1); print $3, $4, $1, $2, length($10), $5}' > txtfiles/"$file2"".txt"
done
