#!/bin/bash
#SBATCH --job-name=Remap6Leaves
#SBATCH --partition=batch
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=8
#SBATCH --time=65:00:00
#SBATCH --mem=200gb

cd $SLURM_SUBMIT_DIR

ml fastp
ml Bowtie2
ml SAMtools

for file in rawdata/*R1*
do
        file2="${file:8:-15}"
        

        fastp -i processed/$file2 -I rawdata/"$file2""_R2.fastq.gz" -o processed/"$file2""R1B.fastq.gz" -O processed/"$file2""R2B.fastq.gz" -U --umi_loc read1 --umi_len 29 --umi_prefix TIR -h html/"$file2"".html" -A -G -Q -L

        fastp -i processed/"$file2""R1B.fastq.gz" -I processed/"$file2""R2B.fastq.gz" -o filtered/"$file2""R1.fastq.gz" -O filtered/"$file2""R2.fastq.gz" --length_required 40 --trim_poly_x --cut_tail --adapter_fasta /scratch/jts34805/adapter2.1.fa




bowtie2 --threads 8 -x /scratch/jts34805/W22Build/W22chrscaff --phred33 -X 1000 --no-mixed --no-discordant -1 filtered/"$file2""R1.fastq.gz" -2 filtered/"$file2""R2.fastq.gz" | samtools view -@ 8 -b -o mapped/"$file2"".bam"


        samtools sort -@ 8 mapped/"$file2"".bam" -o mapped/"$file2"".bam"
        samtools index -@ 8 mapped/"$file2"".bam"

        samtools view -f 64 -F 4 mapped/"$file2"".bam" | awk -F" " '{split($1, a, "_"); substr(a[2],1,29)}' > txtfiles/"$file2"".txt"

done
