#!/bin/bash
#SBATCH --job-name=Decemeber2023Sequencing
#SBATCH --partition=batch
#SBATCH --ntasks=8
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=2
#SBATCH --time=165:00:00
#SBATCH --mem=200gb

cd $SLURM_SUBMIT_DIR

ml fastp
ml Bowtie2
ml SAMtools
ml UMI-tools

for file in filtered/*R1*
do
        file2="${file:9:-12}"

bowtie2 --threads 8 -x /scratch/jts34805/W22Build/W22chrscaff --phred33 -X 1000 --no-mixed --no-discordant -1 filtered/"$file2""R1.fastq.gz" -2 filtered/"$file2""R2.fastq.gz" | samtools view -@ 8 -b -o mapped/"$file2"".bam"


        samtools sort -@ 8 mapped/"$file2"".bam" -o mapped/"$file2"".bam"
        samtools index -@ 8 mapped/"$file2"".bam"


        umi_tools group -I mapped/"$file2"".bam" --paired --chimeric-pairs discard --unpaired-reads discard --output-bam -S dedup/"$file2"".Dedup.bam"


        samtools view -f 64 -F 4 dedup/"$file2"".Dedup.bam" | awk -F" " '{split($1, a, "_"); print $3, $4, $8, $9, substr(a[2],1,6), substr(a[3],1,8), $5, length($10),substr(a[4],1,10), substr(a[4],11,11)}' > txtfiles/"$file2""W22.txt"

done
