#!/bin/bash
#SBATCH --job-name=remaketxtS78
#SBATCH --partition=batch
#SBATCH --ntasks=8
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=2
#SBATCH --time=165:00:00
#SBATCH --mem=30gb

ml Bowtie2
ml SAMtools
ml UMI-tools

bowtie2 --threads 8 -x /scratch/jts34805/B73V5Build/B73V5 --phred33 -X 1000 --no-mixed --no-discordant -1 filtered/Brad_S78-1A_S19_R1.fastq.gz -2 filtered/Brad_S78-1A_S19_R2.fastq.gz | samtools view -@ 8 -b -o mapped/Brad_S78-1A_S19_.bam
bowtie2 --threads 8 -x /scratch/jts34805/B73V5Build/B73V5 --phred33 -X 1000 --no-mixed --no-discordant -1 filtered/Brad_S78-1B_Glume_S29_R1.fastq.gz -2 filtered/Brad_S78-1B_Glume_S29_R2.fastq.gz | samtools view -@ 8 -b -o mapped/Brad_S78-1B_Glume_S29_.bam

samtools sort -@ 8 mapped/Brad_S78-1A_S19_.bam -o mapped/Brad_S78-1A_S19_.bam
        samtools index -@ 8 mapped/Brad_S78-1A_S19_.bam


        umi_tools group -I mapped/Brad_S78-1A_S19_.bam --paired --chimeric-pairs discard --unpaired-reads discard --output-bam -S dedup/Brad_S78-1A_S19_.Dedup.bam


        samtools view -f 64 -F 4 dedup/Brad_S78-1A_S19_.Dedup.bam | awk -F" " '{split($1, a, "_"); print $3, $4, $8, $9, substr(a[2],1,6), substr(a[3],1,8), $5, length($10),substr(a[4],1,10), substr(a[4],11,11)}' > txtfiles/Brad_S78-1A_S19_.txt

samtools sort -@ 8 mapped/Brad_S78-1B_Glume_S29_.bam -o mapped/Brad_S78-1B_Glume_S29_.bam
        samtools index -@ 8 mapped/Brad_S78-1B_Glume_S29_.bam


        umi_tools group -I mapped/Brad_S78-1B_Glume_S29_.bam --paired --chimeric-pairs discard --unpaired-reads discard --output-bam -S dedup/Brad_S78-1B_Glume_S29_.Dedup.bam


        samtools view -f 64 -F 4 dedup/Brad_S78-1B_Glume_S29_.Dedup.bam | awk -F" " '{split($1, a, "_"); print $3, $4, $8, $9, substr(a[2],1,6), substr(a[3],1,8), $5, length($10),substr(a[4],1,10), substr(a[4],11,11)}' > txtfiles/Brad_S78-1B_Glume_S29_.txt


